## Figure 3

```{r}
# load & install packages --------------------------------------------------------------------
library("pacman")
p_load_gh("paul-buerkner/brms", "reispat/lazerhawk", "anthonynorth/rscodeio", update=FALSE)
p_load("tidyverse", "tidybayes", "car", "pastecs", "lme4", "lmerTest", 
       "sjPlot", "MASS", "nlme", "reshape2", "interplot", "ggpubr", "scales", "RColorBrewer", "ggmcmc", "ggthemes", 
       "ggridges", "ggpubr", "devtools", "ggeffects", "mice", "dplyr", "ggplot2", "readr", "svglite", "grid", 
       "lazerhawk", "gridSVG", "tinytex", "mousetrap", "easystats", "ltm", "misty", update=FALSE)
warnings()

# load & configure rstan, brms & loo
library("rstan")
options(mc.cores=parallel::detectCores())
mc.cores = parallel::detectCores()
rstan_options(auto_write=TRUE)
library("brms")
library("loo")
```

```{r}
# load data (acoustic)--------------------------------------------------------------------
ds_accs_df_acoustic <- read.csv("./data/bayes/ds_accs_df_acoustic.csv")
ds_accs_df_acoustic$subject_id <- as.factor(ds_accs_df_acoustic$subject_id)
ds_accs_df_acoustic$distractor <- as.factor(ds_accs_df_acoustic$distractor)

# z-score variables
ds_accs_df_acoustic$acc_avg_z = scale(ds_accs_df_acoustic$acc_avg, center=TRUE, scale=TRUE)
ds_accs_df_acoustic$performance_z = scale(ds_accs_df_acoustic$performance, center=TRUE, scale=TRUE)
ds_accs_df_acoustic$difficulty_z = scale(ds_accs_df_acoustic$difficulty, center=TRUE, scale=TRUE)
ds_accs_df_acoustic$motivation_z = scale(ds_accs_df_acoustic$motivation, center=TRUE, scale=TRUE)
```

```{r}
# calculate models (acoustic) ---------------------------------------------------
# performance
model_aud_perf <- brm(performance ~ 1 + acc_avg + (1 | subject_id),
                      data=ds_accs_df_acoustic, init_r=0.1, warmup=500, iter=10000, control=list(adapt_delta=0.99,
                                                                                            max_treedepth=12), family=student,
                      cores=mc.cores, chains=4, seed=777)

model_aud_perf_z <- brm(performance_z ~ 1 + acc_avg_z + (1 | subject_id),
                      data=ds_accs_df_acoustic, init_r=0.1, warmup=500, iter=10000, control=list(adapt_delta=0.99,
                                                                                            max_treedepth=12), family=student,
                      cores=mc.cores, chains=4, seed=777)
# difficulty
model_aud_diff <- brm(difficulty ~ 1 + acc_avg + (1 | subject_id),
                      data=ds_accs_df_acoustic, init_r=0.1, warmup=500, iter=10000, control=list(adapt_delta=0.99,
                                                                                            max_treedepth=12), family=student,
                      cores=mc.cores, chains=4, seed=777)
model_aud_diff_z <- brm(difficulty_z ~ 1 + acc_avg_z + (1 | subject_id),
                      data=ds_accs_df_acoustic, init_r=0.1, warmup=500, iter=10000, control=list(adapt_delta=0.99,
                                                                                            max_treedepth=12), family=student,
                      cores=mc.cores, chains=4, seed=777)

# motivation
model_aud_mot <- brm(motivation ~ 1 + acc_avg + (1 | subject_id),
                      data=ds_accs_df_acoustic, init_r=0.1, warmup=500, iter=10000, control=list(adapt_delta=0.99,
                                                                                            max_treedepth=12), family=student,
                      cores=mc.cores, chains=4, seed=777)
model_aud_mot_z <- brm(motivation_z ~ 1 + acc_avg_z + (1 | subject_id),
                      data=ds_accs_df_acoustic, init_r=0.1, warmup=500, iter=10000, control=list(adapt_delta=0.99,
                                                                                            max_treedepth=12), family=student,
                      cores=mc.cores, chains=4, seed=777)

```

```{r}
# plot performance
c_eff_perf <- plot(conditional_effects(model_acc_perf, prob = 0.89), points=TRUE, point_args=list(size = 5))

c_eff_perf_plot <- c_eff_perf[[1]] + xlab("Neural tracking (r)") + ylab("Performance (%)") +
  theme_classic() +
  scale_x_continuous(expand=c(0, 0), limits=c(0, 0.2)) + scale_y_continuous(expand=c(0, 0), limits=c(20, 102))
c_eff_perf_plot

# plot difficulty
c_eff_diff <- plot(conditional_effects(model_acc_diff, prob = 0.89), points=TRUE, point_args=list(size = 5))

c_eff_diff_plot <- c_eff_diff[[1]] + xlab("Neural tracking (r)") + ylab("Difficulty (not -> very)") + 
  theme_classic() + 
  scale_x_continuous(expand=c(0, 0), limits=c(0, 0.2)) + scale_y_continuous(expand=c(0, 0), limits=c(0.9, 5.1))
c_eff_diff_plot
```

